name: sikerja_ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/banua-coder/sikerja-ui-kit.git

environment:
  sdk: ">=3.0.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  extended_image: ^8.0.2
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  google_fonts: ^5.1.0
  lottie: ^2.5.0
  nil: ^1.1.1
  skeletonizer: ^0.7.0
  tap_debouncer: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/icons/
    - assets/illustration/
    - assets/logo/

flutter_gen:
  output: lib/src/core/assets/gen
  integrations:
    lottie: true
